config/routes.rb
Rails.application.routes.draw do
  get 'items/create'
  resources :lists do
    resources :items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'site/index'
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list
    validates :description, :presence => true

    STATUS = {
        :incomplete => 0,
        :complete => 1
    }

    def complete?
        self.status == STATUS[:complete]
    end

    def incomplete?
        self.status == STATUS[:incomplete]
    end
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items
    validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
   if @item.save
    redirect_to list_path(@list)
   else
    render "lists/show"
  end
end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)

  redirect_to list_path(@item.list)
end

def destroy
  @item = Item.find(params[:id])
@item.destroy
redirect_to list_path(@item.list)
end

  private
  def item_params
    params.require(:item).permit(:description, :status)
  end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @list = List.new
        @lists = List.all
    end

    def new
        @list = List.new
    end

    def show
        @list = List.find(params[:id])
        @item = Item.new
    end 

    def create 
        @list = List.new(list_params) 
       if @list.save
           redirect_to list_path(@list)
       else
        @lists = List.all
        render :index
       end
    end 

    private
    def list_params
    params.require(:list).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def li_for_item(item)
    content_tag_for :li, item, :class => li_class_for_item(item) do
      yield
    end
  end

  def form_for_item_status(item)
    form_for([item.list, item]) do |f|
      f.check_box :status, :class => "toggle", :checked => item.complete?
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
    <div class="view">
    <%= form_for_item_status(item) %>

    <label><%= item.description %></label>

    <%= button_to "x", list_item_path(item.list, item), :method => "delete", :class => "destroy" %>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMvc</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
			<header class="header">
                <h1>Shopping List</h1>
                <%= form_for(@list) do |f| %>
                <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first|| "Enter a new name...") %> 
                <%= f.submit :style => "display: none" %>  
                <% end %>
                </form>
			</header>
			<section class="main">
            <input class="toggle-all" type="checkbox">
            <label for="toggle-all">Mark all as complete</label>
                <ul class="todo-list">
                <% @lists.each do |list| %>
                  <li>
                   <div class="view">
                      <label><%= link_to list.name, list_path(list) %></label>
                   </div>
                  </li>
                  <% end %>
                </ul>
			</section>
			<footer class="footer" style="display: block;">
				
			</footer>
		</section>

app/views/lists/show.html.erb
<section class="todoapp">
  <header class="header">
    <h1><%= @list.name %></h1>
    <%= form_for([@list, @item]) do |f| %>
      <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item...") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>
  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <%= render :collection => @list.items, :partial => "items/item_li", :as => :item %>
    </ul>
  </section>
  <footer class="footer">
  </footer>
</section>